spring.application.name=MealMatch

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mealmatch?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=TeamFABSuperSecretKeyForJWTSigning2024MealPlatform
jwt.expiration=86400000

server.port=8080
server.address=0.0.0.0
